### ISSUE TITLE
OSError: CUDA_HOME environment variable is not set. 

### ISSUE THREAD

**Issue by BladeTransformerLLC** [j-alex-hanson/gaussian-splatting-pup#4]
Hi there. Installing the compress-diff-gaussian-rasterization submodule fails due to the missing CUDA_HOME environment variable despite it being already set correctly.

```
Installing pip dependencies: - Ran pip subprocess with arguments:
['C:\\Users\\satyoshi\\anaconda3\\envs\\gaussian_splatting_pup\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'D:\\data\\programming\\gaussian-splatting-pup\\condaenv.p7wx86bh.requirements.txt', '--exists-action=b']
Pip subprocess output:
Processing d:\data\programming\gaussian-splatting-pup\submodules\compress-diff-gaussian-rasterization
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\data\programming\gaussian-splatting-pup\submodules\compress-diff-gaussian-rasterization\setup.py", line 21, in <module>
          CUDAExtension(
        File "C:\Users\satyoshi\anaconda3\envs\gaussian_splatting_pup\lib\site-packages\torch\utils\cpp_extension.py", line 1076, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "C:\Users\satyoshi\anaconda3\envs\gaussian_splatting_pup\lib\site-packages\torch\utils\cpp_extension.py", line 1214, in library_paths
          paths.append(_join_cuda_home(lib_dir))
        File "C:\Users\satyoshi\anaconda3\envs\gaussian_splatting_pup\lib\site-packages\torch\utils\cpp_extension.py", line 2416, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

```
echo $env:CUDA_HOME
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
```

**Comment by j-alex-hanson** [comment]
This looks like an environment issue and unhelpful pytorch error message.
https://discuss.pytorch.org/t/problem-with-custom-extensions-and-pytorch-installation-using-anaconda/188446

You likely just need install the CUDA toolkit corresponding to your CUDA version, since that's needed for building custom pytorch modules (which is effectively what pip is doing above).

For reference, I just install the CUDA meta package in my environments which includes all the necessary CUDA dependencies.

Here's what I use for PUP 3D-GS:
```
conda install -c "nvidia/label/cuda-11.8.0" cuda
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118
```

Hope this helps!
